# Generated by Django 5.0.1 on 2024-02-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('auther_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('number_of_pages', models.IntegerField()),
                ('avilable', models.BooleanField(default=True)),
            ],
        ),
    ]
