# Generated by Django 5.0.1 on 2024-02-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('romantic', 'romantic'), ('horrible', 'horrible'), ('advanture', 'advanture')], max_length=50)),
            ],
        ),
    ]
