# Generated by Django 5.0.1 on 2024-02-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_category_rel_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='rel',
        ),
        migrations.AddField(
            model_name='category',
            name='rel',
            field=models.ManyToManyField(to='lms_app.book'),
        ),
    ]
