# Generated by Django 5.0.1 on 2024-02-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_remove_book_auther_name_remove_book_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='avilable',
            new_name='active',
        ),
    ]
