# Generated by Django 5.0.1 on 2024-02-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0010_book_total_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='book_name',
        ),
    ]
